"""Mock data for Employee subsystem."""

MOCK_DEPARTMENTS = [
    {
        "id": "DEP-TECH",
        "name": "Phòng Kỹ thuật",
        "code": "TECH",
        "manager_id": "NV009",
        "manager_name": "Ngô Quang I",
        "member_count": 5,
        "description": "Phụ trách phát triển nền tảng phần mềm, hạ tầng đám mây và hệ thống AI.",
    },
    {
        "id": "DEP-HR",
        "name": "Phòng Nhân sự",
        "code": "HR",
        "manager_id": "NV002",
        "manager_name": "Trần Thị B",
        "member_count": 2,
        "description": "Phụ trách tuyển dụng, đào tạo, chế độ đãi ngộ và quản trị nhân sự.",
    },
    {
        "id": "DEP-ACC",
        "name": "Phòng Kế toán",
        "code": "ACC",
        "manager_id": "NV006",
        "manager_name": "Đỗ Thị F",
        "member_count": 1,
        "description": "Quản lý dòng tiền, báo cáo tài chính và thanh toán lương thưởng.",
    },
    {
        "id": "DEP-SALES",
        "name": "Phòng Kinh doanh",
        "code": "SALES",
        "manager_id": "NV007",
        "manager_name": "Bùi Văn G",
        "member_count": 1,
        "description": "Phát triển thị trường, tìm kiếm khách hàng doanh nghiệp và đối tác.",
    },
    {
        "id": "DEP-MKT",
        "name": "Phòng Marketing",
        "code": "MKT",
        "manager_id": "NV008",
        "manager_name": "Hoàng Thu H",
        "member_count": 1,
        "description": "Xây dựng thương hiệu, truyền thông sản phẩm và tiếp thị số.",
    },
]

MOCK_EMPLOYEES = [
    {
        "id": "NV001",
        "name": "Nguyễn Văn A",
        "email": "nguyen.vana@company.com",
        "phone": "0912345601",
        "department_id": "DEP-TECH",
        "department_name": "Phòng Kỹ thuật",
        "position": "Kỹ sư Phần mềm",
        "join_date": "2023-01-15",
        "status": "active",
        "notes": "Chuyên trách phát triển backend và microservices.",
    },
    {
        "id": "NV002",
        "name": "Trần Thị B",
        "email": "tran.thib@company.com",
        "phone": "0912345602",
        "department_id": "DEP-HR",
        "department_name": "Phòng Nhân sự",
        "position": "Trưởng phòng Nhân sự",
        "join_date": "2022-03-01",
        "status": "active",
        "notes": "Quản lý chiến lược nhân sự và văn hóa doanh nghiệp.",
    },
    {
        "id": "NV003",
        "name": "Lê Hoàng C",
        "email": "le.hoangc@company.com",
        "phone": "0912345603",
        "department_id": "DEP-HR",
        "department_name": "Phòng Nhân sự",
        "position": "Chuyên viên Tuyển dụng",
        "join_date": "2023-06-10",
        "status": "active",
        "notes": "Phối hợp với phân hệ tuyển dụng và quản lý hồ sơ ứng viên.",
    },
    {
        "id": "NV004",
        "name": "Phạm Minh D",
        "email": "pham.minhd@company.com",
        "phone": "0912345604",
        "department_id": "DEP-TECH",
        "department_name": "Phòng Kỹ thuật",
        "position": "Frontend Developer",
        "join_date": "2023-08-20",
        "status": "active",
        "notes": "Chịu trách nhiệm xây dựng giao diện Dashboard và Chatbot Web UI.",
    },
    {
        "id": "NV005",
        "name": "Vũ Hải E",
        "email": "vu.haie@company.com",
        "phone": "0912345605",
        "department_id": "DEP-TECH",
        "department_name": "Phòng Kỹ thuật",
        "position": "Backend Developer",
        "join_date": "2024-02-01",
        "status": "active",
        "notes": "Phát triển các API kết nối cơ sở dữ liệu và cache.",
    },
    {
        "id": "NV006",
        "name": "Đỗ Thị F",
        "email": "do.thif@company.com",
        "phone": "0912345606",
        "department_id": "DEP-ACC",
        "department_name": "Phòng Kế toán",
        "position": "Kế toán trưởng",
        "join_date": "2021-11-15",
        "status": "active",
        "notes": "Phụ trách quyết toán thuế và bảng lương.",
    },
    {
        "id": "NV007",
        "name": "Bùi Văn G",
        "email": "bui.vang@company.com",
        "phone": "0912345607",
        "department_id": "DEP-SALES",
        "department_name": "Phòng Kinh doanh",
        "position": "Nhân viên Kinh doanh",
        "join_date": "2024-05-10",
        "status": "active",
        "notes": "Chăm sóc khách hàng B2B khu vực miền Bắc.",
    },
    {
        "id": "NV008",
        "name": "Hoàng Thu H",
        "email": "hoang.thuh@company.com",
        "phone": "0912345608",
        "department_id": "DEP-MKT",
        "department_name": "Phòng Marketing",
        "position": "Marketing Specialist",
        "join_date": "2024-06-01",
        "status": "active",
        "notes": "Triển khai chiến dịch truyền thông đa kênh.",
    },
    {
        "id": "NV009",
        "name": "Ngô Quang I",
        "email": "ngo.quangi@company.com",
        "phone": "0912345609",
        "department_id": "DEP-TECH",
        "department_name": "Phòng Kỹ thuật",
        "position": "DevOps Engineer / Tech Lead",
        "join_date": "2022-01-10",
        "status": "active",
        "notes": "Quản lý hạ tầng CI/CD, Docker và Server deployment.",
    },
    {
        "id": "NV010",
        "name": "Đặng Mai K",
        "email": "dang.maik@company.com",
        "phone": "0912345610",
        "department_id": "DEP-TECH",
        "department_name": "Phòng Kỹ thuật",
        "position": "Product Manager",
        "join_date": "2023-04-05",
        "status": "active",
        "notes": "Định hướng phát triển các sản phẩm AI Agent.",
    },
]
