"""Mock data for Employee subsystem (FME Enterprise)."""

MOCK_DEPARTMENTS = [
    {
        "id": "DEP-TECH",
        "name": "Phòng Kỹ thuật",
        "code": "TECH",
        "manager_id": "NV009",
        "manager_name": "Ngô Quang I",
        "member_count": 5,
        "description": "Phụ trách phát triển nền tảng phần mềm, hạ tầng đám mây và hệ thống AI Agent.",
        "location": "Tầng 5, Tòa nhà FME, Hà Nội",
        "budget_yearly": "5,000,000,000 VND",
    },
    {
        "id": "DEP-HR",
        "name": "Phòng Nhân sự",
        "code": "HR",
        "manager_id": "NV002",
        "manager_name": "Trần Thị B",
        "member_count": 3,
        "description": "Phụ trách tuyển dụng, đào tạo, chế độ đãi ngộ, văn hóa doanh nghiệp và quan hệ lao động.",
        "location": "Tầng 4, Tòa nhà FME, Hà Nội",
        "budget_yearly": "2,200,000,000 VND",
    },
    {
        "id": "DEP-ACC",
        "name": "Phòng Kế toán",
        "code": "ACC",
        "manager_id": "NV006",
        "manager_name": "Đỗ Thị F",
        "member_count": 2,
        "description": "Quản lý dòng tiền, báo cáo tài chính, quyết toán thuế và thanh toán bảng lương.",
        "location": "Tầng 4, Tòa nhà FME, Hà Nội",
        "budget_yearly": "1,500,000,000 VND",
    },
    {
        "id": "DEP-SALES",
        "name": "Phòng Kinh doanh",
        "code": "SALES",
        "manager_id": "NV007",
        "manager_name": "Bùi Văn G",
        "member_count": 3,
        "description": "Phát triển thị trường, tìm kiếm khách hàng doanh nghiệp B2B và mở rộng đối tác chiến lược.",
        "location": "Tầng 3, Tòa nhà FME, TP. Hồ Chí Minh",
        "budget_yearly": "3,800,000,000 VND",
    },
    {
        "id": "DEP-MKT",
        "name": "Phòng Marketing",
        "code": "MKT",
        "manager_id": "NV008",
        "manager_name": "Hoàng Thu H",
        "member_count": 2,
        "description": "Xây dựng thương hiệu doanh nghiệp, chiến dịch truyền thông đa kênh và tiếp thị số.",
        "location": "Tầng 3, Tòa nhà FME, Hà Nội",
        "budget_yearly": "2,800,000,000 VND",
    },
    {
        "id": "DEP-OPS",
        "name": "Phòng Vận hành",
        "code": "OPS",
        "manager_id": "NV015",
        "manager_name": "Đỗ Hải Nam",
        "member_count": 3,
        "description": "Vận hành hệ thống, hỗ trợ kỹ thuật khách hàng 24/7 và đảm bảo SLAs dịch vụ.",
        "location": "Tầng 2, Tòa nhà FME, Đà Nẵng",
        "budget_yearly": "1,800,000,000 VND",
    },
    {
        "id": "DEP-BOD",
        "name": "Ban Giám đốc",
        "code": "BOD",
        "manager_id": "NV020",
        "manager_name": "Phan Đình Tuấn",
        "member_count": 2,
        "description": "Hoạch định chiến lược tăng trưởng tổng thể và điều hành hoạt động toàn công ty.",
        "location": "Tầng 6, Tòa nhà FME, Hà Nội",
        "budget_yearly": "8,000,000,000 VND",
    },
]

MOCK_EMPLOYEES = [
    {
        "id": "NV001",
        "name": "Nguyễn Văn A",
        "email": "nguyen.vana@company.com",
        "phone": "0912345601",
        "department_id": "DEP-TECH",
        "department_name": "Phòng Kỹ thuật",
        "position": "Kỹ sư Phần mềm",
        "join_date": "2023-01-15",
        "status": "active",
        "gender": "Nam",
        "birth_date": "1996-05-12",
        "education": "Kỹ sư CNTT - Đại học Bách Khoa Hà Nội",
        "skills": ["Python", "FastAPI", "PostgreSQL", "Docker", "Microservices"],
        "contract_type": "Hợp đồng không xác định thời hạn",
        "work_location": "Hà Nội",
        "manager_id": "NV009",
        "manager_name": "Ngô Quang I",
        "notes": "Chuyên trách phát triển backend Core Chatbot và microservices kết nối MCP.",
    },
    {
        "id": "NV002",
        "name": "Trần Thị B",
        "email": "tran.thib@company.com",
        "phone": "0912345602",
        "department_id": "DEP-HR",
        "department_name": "Phòng Nhân sự",
        "position": "Trưởng phòng Nhân sự",
        "join_date": "2022-03-01",
        "status": "active",
        "gender": "Nữ",
        "birth_date": "1990-08-20",
        "education": "Thạc sĩ Quản trị Nhân lực - ĐH Kinh tế Quốc dân",
        "skills": ["Talent Acquisition", "HR Policy", "KPI Evaluation", "Employee Relations"],
        "contract_type": "Hợp đồng không xác định thời hạn",
        "work_location": "Hà Nội",
        "manager_id": "NV020",
        "manager_name": "Phan Đình Tuấn",
        "notes": "Quản lý chiến lược nhân sự, đãi ngộ và văn hóa doanh nghiệp.",
    },
    {
        "id": "NV003",
        "name": "Lê Hoàng C",
        "email": "le.hoangc@company.com",
        "phone": "0912345603",
        "department_id": "DEP-HR",
        "department_name": "Phòng Nhân sự",
        "position": "Chuyên viên Tuyển dụng",
        "join_date": "2023-06-10",
        "status": "active",
        "gender": "Nam",
        "birth_date": "1998-11-04",
        "education": "Cử nhân Luật Lao động - ĐH Luật Hà Nội",
        "skills": ["Headhunting", "Interviewing", "Candidate Sourcing", "Job Portal Management"],
        "contract_type": "Hợp đồng 3 năm",
        "work_location": "Hà Nội",
        "manager_id": "NV002",
        "manager_name": "Trần Thị B",
        "notes": "Phối hợp trực tiếp với phân hệ tuyển dụng và quản lý hồ sơ ứng viên.",
    },
    {
        "id": "NV004",
        "name": "Phạm Minh D",
        "email": "pham.minhd@company.com",
        "phone": "0912345604",
        "department_id": "DEP-TECH",
        "department_name": "Phòng Kỹ thuật",
        "position": "Frontend Developer",
        "join_date": "2023-08-20",
        "status": "active",
        "gender": "Nam",
        "birth_date": "1999-03-15",
        "education": "Cử nhân Khoa học Máy tính - ĐH Công nghệ (VNU)",
        "skills": ["React", "TypeScript", "Tailwind CSS", "Next.js", "WebSocket"],
        "contract_type": "Hợp đồng 3 năm",
        "work_location": "Hà Nội",
        "manager_id": "NV009",
        "manager_name": "Ngô Quang I",
        "notes": "Chịu trách nhiệm xây dựng giao diện Dashboard và Chatbot Web UI.",
    },
    {
        "id": "NV005",
        "name": "Vũ Hải E",
        "email": "vu.haie@company.com",
        "phone": "0912345605",
        "department_id": "DEP-TECH",
        "department_name": "Phòng Kỹ thuật",
        "position": "Backend Developer",
        "join_date": "2024-02-01",
        "status": "active",
        "gender": "Nam",
        "birth_date": "2000-09-28",
        "education": "Kỹ sư Kỹ thuật Phần mềm - Học viện Bưu chính Viễn thông",
        "skills": ["Golang", "Python", "Redis", "Kafka", "PostgreSQL"],
        "contract_type": "Hợp đồng 3 năm",
        "work_location": "Hà Nội",
        "manager_id": "NV009",
        "manager_name": "Ngô Quang I",
        "notes": "Phát triển các API kết nối cơ sở dữ liệu và hạ tầng cache Redis.",
    },
    {
        "id": "NV006",
        "name": "Đỗ Thị F",
        "email": "do.thif@company.com",
        "phone": "0912345606",
        "department_id": "DEP-ACC",
        "department_name": "Phòng Kế toán",
        "position": "Kế toán trưởng",
        "join_date": "2021-11-15",
        "status": "active",
        "gender": "Nữ",
        "birth_date": "1988-02-18",
        "education": "Thạc sĩ Tài chính Doanh nghiệp - Học viện Tài chính",
        "skills": ["Corporate Finance", "Tax Planning", "Financial Auditing", "ERP Accounting"],
        "contract_type": "Hợp đồng không xác định thời hạn",
        "work_location": "Hà Nội",
        "manager_id": "NV020",
        "manager_name": "Phan Đình Tuấn",
        "notes": "Phụ trách quyết toán thuế, báo cáo kiểm toán và bảng lương toàn hệ thống.",
    },
    {
        "id": "NV007",
        "name": "Bùi Văn G",
        "email": "bui.vang@company.com",
        "phone": "0912345607",
        "department_id": "DEP-SALES",
        "department_name": "Phòng Kinh doanh",
        "position": "Trưởng phòng Kinh doanh",
        "join_date": "2022-07-01",
        "status": "active",
        "gender": "Nam",
        "birth_date": "1991-12-05",
        "education": "Cử nhân Quản trị Kinh doanh - ĐH Ngoại thương",
        "skills": ["B2B Sales", "Enterprise Negotiation", "Key Account Management", "CRM"],
        "contract_type": "Hợp đồng không xác định thời hạn",
        "work_location": "TP. Hồ Chí Minh",
        "manager_id": "NV020",
        "manager_name": "Phan Đình Tuấn",
        "notes": "Phát triển thị trường doanh nghiệp B2B và kênh bán hàng khu vực phía Nam.",
    },
    {
        "id": "NV008",
        "name": "Hoàng Thu H",
        "email": "hoang.thuh@company.com",
        "phone": "0912345608",
        "department_id": "DEP-MKT",
        "department_name": "Phòng Marketing",
        "position": "Trưởng phòng Marketing",
        "join_date": "2023-04-15",
        "status": "active",
        "gender": "Nữ",
        "birth_date": "1994-06-30",
        "education": "Cử nhân Truyền thông - Học viện Báo chí & Tuyên truyền",
        "skills": ["Digital Marketing", "Brand Strategy", "Content Strategy", "Performance Ads"],
        "contract_type": "Hợp đồng 3 năm",
        "work_location": "Hà Nội",
        "manager_id": "NV020",
        "manager_name": "Phan Đình Tuấn",
        "notes": "Chỉ đạo chiến dịch truyền thông đa kênh ra mắt nền tảng AI Agent FME.",
    },
    {
        "id": "NV009",
        "name": "Ngô Quang I",
        "email": "ngo.quangi@company.com",
        "phone": "0912345609",
        "department_id": "DEP-TECH",
        "department_name": "Phòng Kỹ thuật",
        "position": "Tech Lead / Giám đốc Kỹ thuật",
        "join_date": "2022-01-10",
        "status": "active",
        "gender": "Nam",
        "birth_date": "1989-10-14",
        "education": "Thạc sĩ Khoa học Máy tính - Đại học Bách Khoa Hà Nội",
        "skills": ["System Architecture", "Cloud Native (K8s, AWS)", "CI/CD", "DevOps", "AI Integration"],
        "contract_type": "Hợp đồng không xác định thời hạn",
        "work_location": "Hà Nội",
        "manager_id": "NV020",
        "manager_name": "Phan Đình Tuấn",
        "notes": "Kiến trúc sư trưởng hệ thống Multi-Agent và hạ tầng Docker/Kubernetes.",
    },
    {
        "id": "NV010",
        "name": "Đặng Mai K",
        "email": "dang.maik@company.com",
        "phone": "0912345610",
        "department_id": "DEP-TECH",
        "department_name": "Phòng Kỹ thuật",
        "position": "Product Manager",
        "join_date": "2023-04-05",
        "status": "active",
        "gender": "Nữ",
        "birth_date": "1993-01-25",
        "education": "Thạc sĩ Quản trị Công nghệ - ĐH Quốc gia Hà Nội",
        "skills": ["Agile/Scrum", "Product Roadmap", "User Experience", "Market Research"],
        "contract_type": "Hợp đồng 3 năm",
        "work_location": "Hà Nội",
        "manager_id": "NV009",
        "manager_name": "Ngô Quang I",
        "notes": "Định hướng phát triển các sản phẩm AI Agent và kết nối nhu cầu người dùng FME.",
    },
    {
        "id": "NV011",
        "name": "Trịnh Quốc L",
        "email": "trinh.quocl@company.com",
        "phone": "0912345611",
        "department_id": "DEP-OPS",
        "department_name": "Phòng Vận hành",
        "position": "QA Lead",
        "join_date": "2023-09-01",
        "status": "active",
        "gender": "Nam",
        "birth_date": "1995-07-19",
        "education": "Kỹ sư Đảm bảo Chất lượng - ĐH Bách Khoa",
        "skills": ["Automation Test", "Selenium", "Pytest", "Load Testing", "Security Testing"],
        "contract_type": "Hợp đồng 3 năm",
        "work_location": "Đà Nẵng",
        "manager_id": "NV015",
        "manager_name": "Đỗ Hải Nam",
        "notes": "Phụ trách kiểm thử tự động, benchmark và đảm bảo chất lượng hệ thống API.",
    },
    {
        "id": "NV012",
        "name": "Võ Hồng M",
        "email": "vo.hongm@company.com",
        "phone": "0912345612",
        "department_id": "DEP-HR",
        "department_name": "Phòng Nhân sự",
        "position": "Chuyên viên Đào tạo & C&B",
        "join_date": "2024-01-15",
        "status": "active",
        "gender": "Nữ",
        "birth_date": "1997-04-08",
        "education": "Cử nhân Quản trị Nhân lực - ĐH Thương mại",
        "skills": ["Compensation & Benefits", "Corporate Training", "HR Software", "Insurance"],
        "contract_type": "Hợp đồng 3 năm",
        "work_location": "Hà Nội",
        "manager_id": "NV002",
        "manager_name": "Trần Thị B",
        "notes": "Quản lý chế độ bảo hiểm, đãi ngộ và lộ trình đào tạo nội bộ.",
    },
    {
        "id": "NV013",
        "name": "Lương Gia N",
        "email": "luong.gian@company.com",
        "phone": "0912345613",
        "department_id": "DEP-ACC",
        "department_name": "Phòng Kế toán",
        "position": "Kế toán viên Thuế & Chi phí",
        "join_date": "2023-10-10",
        "status": "active",
        "gender": "Nam",
        "birth_date": "1999-12-22",
        "education": "Cử nhân Kế toán Kiểm toán - Học viện Tài chính",
        "skills": ["General Accounting", "VAT Invoicing", "Cost Control", "MISA ERP"],
        "contract_type": "Hợp đồng 3 năm",
        "work_location": "Hà Nội",
        "manager_id": "NV006",
        "manager_name": "Đỗ Thị F",
        "notes": "Theo dõi hóa đơn chứng từ, tạm ứng chi phí và hạch toán hàng ngày.",
    },
    {
        "id": "NV014",
        "name": "Dương Thùy O",
        "email": "duong.thuyo@company.com",
        "phone": "0912345614",
        "department_id": "DEP-SALES",
        "department_name": "Phòng Kinh doanh",
        "position": "Account Manager",
        "join_date": "2024-03-01",
        "status": "active",
        "gender": "Nữ",
        "birth_date": "1996-08-11",
        "education": "Cử nhân Kinh tế Quốc tế - ĐH Ngoại thương",
        "skills": ["Account Management", "Client Pitching", "Sales Analytics", "Contract Closing"],
        "contract_type": "Hợp đồng 3 năm",
        "work_location": "TP. Hồ Chí Minh",
        "manager_id": "NV007",
        "manager_name": "Bùi Văn G",
        "notes": "Phụ trách chăm sóc nhóm khách hàng khối Ngân hàng và Tài chính.",
    },
    {
        "id": "NV015",
        "name": "Đỗ Hải Nam",
        "email": "do.hainam@company.com",
        "phone": "0912345615",
        "department_id": "DEP-OPS",
        "department_name": "Phòng Vận hành",
        "position": "Trưởng phòng Vận hành",
        "join_date": "2022-09-15",
        "status": "active",
        "gender": "Nam",
        "birth_date": "1991-05-03",
        "education": "Kỹ sư Điện tử Viễn thông - ĐH Bách Khoa Đà Nẵng",
        "skills": ["IT Infrastructure", "Service Management", "Incident Response", "ITIL"],
        "contract_type": "Hợp đồng không xác định thời hạn",
        "work_location": "Đà Nẵng",
        "manager_id": "NV020",
        "manager_name": "Phan Đình Tuấn",
        "notes": "Quản lý trung tâm dữ liệu và điều phối đội hỗ trợ kỹ thuật khách hàng.",
    },
    {
        "id": "NV016",
        "name": "Lâm Quốc P",
        "email": "lam.quocp@company.com",
        "phone": "0912345616",
        "department_id": "DEP-OPS",
        "department_name": "Phòng Vận hành",
        "position": "System Administrator",
        "join_date": "2023-11-01",
        "status": "active",
        "gender": "Nam",
        "birth_date": "1998-02-14",
        "education": "Cử nhân Mạng máy tính - ĐH Bách Khoa Đà Nẵng",
        "skills": ["Linux Admin", "Network Security", "Monitoring (Prometheus, Grafana)", "Backup"],
        "contract_type": "Hợp đồng 3 năm",
        "work_location": "Đà Nẵng",
        "manager_id": "NV015",
        "manager_name": "Đỗ Hải Nam",
        "notes": "Trực vận hành ca đêm và bảo trì hệ thống máy chủ định kỳ.",
    },
    {
        "id": "NV017",
        "name": "Ngô Bảo Q",
        "email": "ngo.baoq@company.com",
        "phone": "0912345617",
        "department_id": "DEP-MKT",
        "department_name": "Phòng Marketing",
        "position": "Content Creator / Copywriter",
        "join_date": "2024-05-15",
        "status": "active",
        "gender": "Nam",
        "birth_date": "2001-10-09",
        "education": "Cử nhân Báo chí - ĐH Khoa học Xã hội & Nhân văn",
        "skills": ["SEO Copywriting", "Social Media", "Video Scripting", "PR Articles"],
        "contract_type": "Thử việc",
        "work_location": "Hà Nội",
        "manager_id": "NV008",
        "manager_name": "Hoàng Thu H",
        "notes": "Sản xuất nội dung giới thiệu tính năng sản phẩm trên website và fanpage.",
    },
    {
        "id": "NV018",
        "name": "Tạ Diệu R",
        "email": "ta.dieur@company.com",
        "phone": "0912345618",
        "department_id": "DEP-SALES",
        "department_name": "Phòng Kinh doanh",
        "position": "Sales Executive B2B",
        "join_date": "2024-06-01",
        "status": "active",
        "gender": "Nữ",
        "birth_date": "2000-01-17",
        "education": "Cử nhân Thương mại Quốc tế - ĐH Kinh tế TP.HCM",
        "skills": ["Cold Calling", "Lead Generation", "Customer Care", "Sales CRM"],
        "contract_type": "Hợp đồng 3 năm",
        "work_location": "TP. Hồ Chí Minh",
        "manager_id": "NV007",
        "manager_name": "Bùi Văn G",
        "notes": "Tìm kiếm khách hàng tiềm năng cho giải pháp AI Chatbot doanh nghiệp.",
    },
    {
        "id": "NV019",
        "name": "Đinh Thành S",
        "email": "dinh.thanhs@company.com",
        "phone": "0912345619",
        "department_id": "DEP-BOD",
        "department_name": "Ban Giám đốc",
        "position": "Phó Tổng Giám đốc Vận hành (COO)",
        "join_date": "2021-06-01",
        "status": "active",
        "gender": "Nam",
        "birth_date": "1985-09-08",
        "education": "MBA - National University of Singapore",
        "skills": ["Operations Excellence", "Corporate Governance", "Change Management", "M&A"],
        "contract_type": "Hợp đồng không xác định thời hạn",
        "work_location": "Hà Nội",
        "manager_id": "NV020",
        "manager_name": "Phan Đình Tuấn",
        "notes": "Điều hành trực tiếp khối Vận hành, Kế toán và Kinh doanh.",
    },
    {
        "id": "NV020",
        "name": "Phan Đình Tuấn",
        "email": "phan.dinhtuan@company.com",
        "phone": "0912345620",
        "department_id": "DEP-BOD",
        "department_name": "Ban Giám đốc",
        "position": "Tổng Giám đốc (CEO)",
        "join_date": "2020-01-01",
        "status": "active",
        "gender": "Nam",
        "birth_date": "1982-04-12",
        "education": "Tiến sĩ Khoa học Máy tính - Đại học Tokyo, Nhật Bản",
        "skills": ["Visionary Leadership", "AI Strategy", "Fundraising", "Global Expansion"],
        "contract_type": "Hợp đồng không xác định thời hạn",
        "work_location": "Hà Nội",
        "manager_id": None,
        "manager_name": None,
        "notes": "Nhà sáng lập kiêm Tổng Giám đốc điều hành toàn bộ tập đoàn FME.",
    },
]

MOCK_CONTRACTS = [
    {"contract_id": "HD-2020-001", "employee_id": "NV020", "employee_name": "Phan Đình Tuấn", "type": "Hợp đồng không xác định thời hạn", "start_date": "2020-01-01", "status": "active"},
    {"contract_id": "HD-2022-009", "employee_id": "NV009", "employee_name": "Ngô Quang I", "type": "Hợp đồng không xác định thời hạn", "start_date": "2022-01-10", "status": "active"},
    {"contract_id": "HD-2022-002", "employee_id": "NV002", "employee_name": "Trần Thị B", "type": "Hợp đồng không xác định thời hạn", "start_date": "2022-03-01", "status": "active"},
    {"contract_id": "HD-2023-001", "employee_id": "NV001", "employee_name": "Nguyễn Văn A", "type": "Hợp đồng không xác định thời hạn", "start_date": "2023-01-15", "status": "active"},
    {"contract_id": "HD-2023-004", "employee_id": "NV004", "employee_name": "Phạm Minh D", "type": "Hợp đồng 3 năm", "start_date": "2023-08-20", "status": "active"},
    {"contract_id": "HD-2024-005", "employee_id": "NV005", "employee_name": "Vũ Hải E", "type": "Hợp đồng 3 năm", "start_date": "2024-02-01", "status": "active"},
]
