"""Mock data for Hiring MCP Server (FME Enterprise)."""

from typing import Dict, List

MOCK_JOB_OPENINGS: List[Dict] = [
    {
        "id": "JOB-001",
        "title": "Kỹ sư Phần mềm Backend",
        "department": "Khối Công nghệ thông tin",
        "open_positions": 3,
        "status": "open",
        "requirements": [
            "Tốt nghiệp Đại học CNTT / Kỹ thuật phần mềm",
            "Thành thạo Python, FastAPI, PostgreSQL, Docker",
            "Tối thiểu 3 năm kinh nghiệm phát triển backend",
        ],
        "salary_range": "30,000,000 - 50,000,000 VND",
        "created_date": "2026-08-01",
    },
    {
        "id": "JOB-002",
        "title": "Chuyên viên Phân tích Dữ liệu",
        "department": "Khối Dữ liệu & AI",
        "open_positions": 5,
        "status": "open",
        "requirements": [
            "Tốt nghiệp Toán - Tin / Khoa học máy tính",
            "Thành thạo SQL, Python, PowerBI / Tableau",
            "Tối thiểu 2 năm kinh nghiệm phân tích dữ liệu doanh nghiệp",
        ],
        "salary_range": "18,000,000 - 28,000,000 VND",
        "created_date": "2026-08-05",
    },
    {
        "id": "JOB-003",
        "title": "Kỹ sư AI / Machine Learning",
        "department": "Khối Công nghệ thông tin",
        "open_positions": 2,
        "status": "open",
        "requirements": [
            "Python, LangChain, MCP Protocol, LLM",
            "Hiểu biết về NLP, Deep Learning và kiến trúc Agent",
            "Tối thiểu 2 năm kinh nghiệm nghiên cứu và triển khai AI",
        ],
        "salary_range": "25,000,000 - 45,000,000 VND",
        "created_date": "2026-08-10",
    },
    {
        "id": "JOB-004",
        "title": "Chuyên viên Quản trị Nhân sự",
        "department": "Phòng Nhân sự",
        "open_positions": 1,
        "status": "open",
        "requirements": [
            "Tốt nghiệp Quản trị nhân sự / Luật lao động",
            "Am hiểu luật lao động và quy trình tuyển dụng nhân sự",
            "Kỹ năng phỏng vấn, đánh giá KPI và thương lượng đãi ngộ",
        ],
        "salary_range": "15,000,000 - 22,000,000 VND",
        "created_date": "2026-08-12",
    },
    {
        "id": "JOB-005",
        "title": "Kỹ sư Vận hành Hệ thống (DevOps/SRE)",
        "department": "Khối Vận hành",
        "open_positions": 2,
        "status": "closed",
        "requirements": [
            "Thành thạo Linux, Docker, Kubernetes, CI/CD pipeline",
            "Có kinh nghiệm quản trị hạ tầng Cloud (AWS/GCP/Azure)",
        ],
        "salary_range": "22,000,000 - 35,000,000 VND",
        "created_date": "2026-07-15",
    },
    {
        "id": "JOB-006",
        "title": "Kỹ sư Frontend (React/TypeScript)",
        "department": "Khối Công nghệ thông tin",
        "open_positions": 2,
        "status": "open",
        "requirements": [
            "Thành thạo React, TypeScript, Tailwind CSS",
            "Có kinh nghiệm làm việc với REST API, WebSocket",
            "Tối thiểu 2 năm kinh nghiệm phát triển web frontend",
        ],
        "salary_range": "20,000,000 - 35,000,000 VND",
        "created_date": "2026-08-15",
    },
]

MOCK_CANDIDATES: List[Dict] = [
    {
        "id": "UV001",
        "name": "Nguyễn Văn An",
        "email": "nguyenvanan@gmail.com",
        "phone": "0912345678",
        "position": "Kỹ sư Phần mềm Backend",
        "job_id": "JOB-001",
        "status": "pending_interview",
        "experience_years": 4.5,
        "skills": ["Python", "FastAPI", "PostgreSQL", "Docker", "REST API", "Microservices"],
        "applied_date": "2026-08-08",
        "notes": "Hồ sơ đạt yêu cầu vòng loại, đang chờ xếp lịch phỏng vấn chuyên môn",
    },
    {
        "id": "UV002",
        "name": "Trần Thị Bích",
        "email": "tranbich99@gmail.com",
        "phone": "0987654321",
        "position": "Chuyên viên Phân tích Dữ liệu",
        "job_id": "JOB-002",
        "status": "interviewing",
        "experience_years": 2.0,
        "skills": ["SQL", "Python", "PowerBI", "Data Modeling", "Trực quan hóa dữ liệu"],
        "applied_date": "2026-08-10",
        "notes": "Đã qua vòng 1, chuẩn bị phỏng vấn vòng 2 cùng Trưởng nhóm Phân tích",
    },
    {
        "id": "UV003",
        "name": "Lê Hoàng Nam",
        "email": "nam.lehoang@gmail.com",
        "phone": "0903123456",
        "position": "Kỹ sư AI / Machine Learning",
        "job_id": "JOB-003",
        "status": "pending_interview",
        "experience_years": 3.0,
        "skills": ["Python", "FastAPI", "LangChain", "MCP Protocol", "PyTorch", "Docker"],
        "applied_date": "2026-08-14",
        "notes": "CV ấn tượng về mảng LLM Agent, chờ phỏng vấn kỹ thuật",
    },
    {
        "id": "UV004",
        "name": "Phạm Minh Đức",
        "email": "duc.pm@outlook.com",
        "phone": "0934567890",
        "position": "Kỹ sư AI / Machine Learning",
        "job_id": "JOB-003",
        "status": "offered",
        "experience_years": 5.0,
        "skills": ["Python", "Computer Vision", "Deep Learning", "MLOps", "Kubernetes"],
        "applied_date": "2026-08-02",
        "notes": "Đã vượt qua 2 vòng phỏng vấn với điểm xuất sắc. Đã gửi thư mời nhận việc",
    },
    {
        "id": "UV005",
        "name": "Đỗ Hoàng Lan",
        "email": "lan.dohoang@yahoo.com",
        "phone": "0971239876",
        "position": "Chuyên viên Quản trị Nhân sự",
        "job_id": "JOB-004",
        "status": "pending_interview",
        "experience_years": 3.5,
        "skills": ["Tuyển dụng", "Đào tạo", "Luật lao động", "Đánh giá KPI"],
        "applied_date": "2026-08-15",
        "notes": "Đang chờ phỏng vấn với Trưởng phòng Nhân sự",
    },
    {
        "id": "UV006",
        "name": "Vũ Hải Đăng",
        "email": "haidang.vu@gmail.com",
        "phone": "0945678123",
        "position": "Kỹ sư Vận hành Hệ thống",
        "job_id": "JOB-005",
        "status": "screening",
        "experience_years": 1.0,
        "skills": ["Linux", "Docker", "CI/CD", "Monitoring cơ bản"],
        "applied_date": "2026-08-18",
        "notes": "Đang duyệt hồ sơ",
    },
    {
        "id": "UV007",
        "name": "Ngô Thị Mai",
        "email": "maingo.dr@gmail.com",
        "phone": "0918765432",
        "position": "Kỹ sư Phần mềm Backend",
        "job_id": "JOB-001",
        "status": "rejected",
        "experience_years": 1.0,
        "skills": ["Python", "Django", "MySQL"],
        "applied_date": "2026-08-03",
        "notes": "Chưa đủ số năm kinh nghiệm theo tiêu chí vị trí",
    },
    {
        "id": "UV008",
        "name": "Lê Văn Hùng",
        "email": "hung.levan@gmail.com",
        "phone": "0981122334",
        "position": "Kỹ sư Frontend (React/TypeScript)",
        "job_id": "JOB-006",
        "status": "applied",
        "experience_years": 2.5,
        "skills": ["React", "TypeScript", "Tailwind CSS", "Redux", "Next.js"],
        "applied_date": "2026-08-20",
        "notes": "Hồ sơ mới nộp, có dự án thực tế tốt với Next.js và Tailwind",
    },
    {
        "id": "UV009",
        "name": "Hoàng Thị Cúc",
        "email": "cuc.hoang@gmail.com",
        "phone": "0978899001",
        "position": "Kỹ sư Đảm bảo Chất lượng (QA Automation)",
        "job_id": "JOB-001",
        "status": "pending_interview",
        "experience_years": 3.0,
        "skills": ["Python", "Pytest", "Selenium", "Postman", "CI/CD"],
        "applied_date": "2026-08-16",
        "notes": "Đã hoàn thành bài test kỹ thuật đạt 90/100 điểm, chờ phỏng vấn chuyên môn",
    },
    {
        "id": "UV010",
        "name": "Phan Đình Trọng",
        "email": "trong.phan@company.vn",
        "phone": "0912998877",
        "position": "Kỹ sư Vận hành Hệ thống (DevOps/SRE)",
        "job_id": "JOB-005",
        "status": "interviewing",
        "experience_years": 4.0,
        "skills": ["Linux", "Kubernetes", "Terraform", "AWS", "Prometheus"],
        "applied_date": "2026-08-07",
        "notes": "Đang phỏng vấn vòng 2 với Giám đốc Kỹ thuật",
    },
    {
        "id": "UV011",
        "name": "Bùi Thị Tuyết",
        "email": "tuyet.bui@hrpro.com",
        "phone": "0933221100",
        "position": "Chuyên viên Quản trị Nhân sự",
        "job_id": "JOB-004",
        "status": "hired",
        "experience_years": 5.0,
        "skills": ["Tech Recruitment", "Headhunting", "Onboarding", "HR Policies"],
        "applied_date": "2026-07-28",
        "notes": "Đã hoàn tất thủ tục ký hợp đồng thử việc, onboard ngày 01/09",
    },
    {
        "id": "UV012",
        "name": "Trần Minh Quang",
        "email": "quang.tran@data.ai",
        "phone": "0909554433",
        "position": "Kỹ sư AI / Machine Learning",
        "job_id": "JOB-003",
        "status": "screening",
        "experience_years": 2.0,
        "skills": ["Python", "PyTorch", "HuggingFace", "RAG", "VectorDB"],
        "applied_date": "2026-08-22",
        "notes": "Hồ sơ nổi bật về kiến trúc RAG, đang sàng lọc hồ sơ",
    },
]

MOCK_INTERVIEWS: List[Dict] = [
    {
        "id": "INT-001",
        "candidate_id": "UV002",
        "candidate_name": "Trần Thị Bích",
        "job_title": "Chuyên viên Phân tích Dữ liệu",
        "interview_date": "2026-08-21",
        "interview_time": "09:00 - 10:00",
        "interviewer": "ThS. Đào Minh Tuấn - Trưởng nhóm Phân tích Dữ liệu",
        "round": 2,
        "status": "scheduled",
    },
    {
        "id": "INT-002",
        "candidate_id": "UV003",
        "candidate_name": "Lê Hoàng Nam",
        "job_title": "Kỹ sư AI / Machine Learning",
        "interview_date": "2026-08-22",
        "interview_time": "14:00 - 15:30",
        "interviewer": "ThS. Phạm Quốc Bảo - Trưởng nhóm AI",
        "round": 1,
        "status": "scheduled",
    },
    {
        "id": "INT-003",
        "candidate_id": "UV001",
        "candidate_name": "Nguyễn Văn An",
        "job_title": "Kỹ sư Phần mềm Backend",
        "interview_date": "2026-08-23",
        "interview_time": "10:30 - 11:30",
        "interviewer": "KS. Hoàng Mai Trang - Trưởng nhóm Kỹ thuật Backend",
        "round": 1,
        "status": "scheduled",
    },
    {
        "id": "INT-004",
        "candidate_id": "UV005",
        "candidate_name": "Đỗ Hoàng Lan",
        "job_title": "Chuyên viên Quản trị Nhân sự",
        "interview_date": "2026-08-25",
        "interview_time": "08:30 - 09:30",
        "interviewer": "Bà Đặng Thu Hà - Trưởng phòng Nhân sự",
        "round": 1,
        "status": "scheduled",
    },
]
